// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI Prisma (migrations, studio) : session pooler (5432), pas le transaction
    // pooler. Fallback sur DATABASE_URL tant que DIRECT_URL n'est pas configuré.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
