// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "prisma/config";

loadEnv({ path: resolve(dirname(fileURLToPath(import.meta.url)), "../../.env") });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: requireDirectUrl(),
  },
});

function requireDirectUrl() {
  const directUrl = process.env["DIRECT_URL"];
  if (!directUrl) {
    throw new Error("DIRECT_URL est requis pour Prisma CLI (pooler session, port 5432).");
  }
  return directUrl;
}
